### ISSUE TITLE
macOS wallet progress

### ISSUE THREAD

**Issue by aaashes** [EmberCoin/Ember#12]
Seen a lot of interest in this from a bunch of circles, so would be good to have both this alongside planned Windows update for next mid month.
Shall commit some test builds over next week with LibreSSL.

**Comment by tagazok** [comment]
Nice ! 
I am waiting forward to testing the macos app :)

**Comment by tagazok** [comment]
Any news on the macos wallet?

**Comment by EmberCoin** [comment]
We have successful builds on dev2 branch for both core and Qt macos and linux wallets. The update releasing this will be soon when we merge dev2 at a ready builds processs.

**Comment by EmberCoin** [comment]
We have just released a tag and an official build here for MacOS: https://github.com/EmberCoin/Ember/releases/tag/v1.1.4

Thanks, and let me know via issue if you have any problems.
