### ISSUE TITLE
Unable to install Ember coin wallet in aws.amazon.com

### ISSUE THREAD

**Issue by a4adky** [EmberCoin/Ember#14]
Unable to install Ember coin wallet in aws.amazon.com , I would like to install Ember coin wallet in aws.amazon.com for POS. Please help provide steps to install Ember coin wallet in aws.amazon.com.

Thanks now I am able to install it.

**Comment by crombiecrunch** [comment]
check your dependencies I run all my coin wallets on aws machines.

**Comment by EmberCoin** [comment]
We could use someone with familiarity with AWS EC2 instances enough to write a guide on the environment.

**Comment by bryce27** [comment]
I am also having trouble installing the wallet. I'm running Ubuntu 17 on Vultr. When I double click the extracted .deb file, it loads to 9% and then stops. It has something to do with unmet libboost dependencies.

**Comment by mtetreault** [comment]
It won't work on ubuntu 17.x because of missong dependencies.

The libboost v is not compatible with our build.

**Comment by EmberCoin** [comment]
Seperate issue. If you're not talking about writing guides on AWS EC2 instances please write your own issue.
