### ISSUE TITLE
Kaspersky detect malware on last wallet

### ISSUE THREAD

**Issue by sciack76** [EmberCoin/Ember#18]
I am on Windows 10 and I have Kaspersky Antivirus. It detects an IRCBot Virus. I cannot install the new wallet. The old wallet is ok.

Please advise.

**Comment by EmberCoin** [comment]
I added connections to irc.lfnet.org/7777 for p2p. AV is fucktarded and thinks all IRC usage is bad by default and they are wrong. We're not a popular enough client to justify white-listing unless I ask for it. I guess I'll go and humbly hat in hand ask them the fucking fuck off already.

"IRCBot Virus" fucking nonsense.

**Comment by sciack76** [comment]
thanks for reply. I am sure about that. I have to figure out a way to white list it, otherwise I cannot use the new wallet. Thanks

**Comment by EmberCoin** [comment]
Try the latest release, if you have any more issues with AV, make another issue as that is a new issue. IRC + an autoupdater were removed for this release: https://github.com/EmberCoin/Ember/releases/tag/v1.1.4

Thanks.
