### ISSUE TITLE
Unable to sync wallet

### ISSUE THREAD

**Issue by mix4rmeix** [EmberCoin/Ember#19]
I'm starting using ember wallet just after the update. I downloaded and started it but the status don't change to synchronized. I also tried to deposit some coins there but nothing happened. How do i "turn it on?"

Thanks!

**Comment by EmberCoin** [comment]
Is this still an issue? Try opening/forwarding port 10024 if so.

**Comment by EmberCoin** [comment]
Also you can run ` -rescan`

In case you need to know how to do that:
right click on the wallet, create shortcut, right click on the shortcut, properties, then in "Target" go to the end, add a space, and add -rescan, hit "ok", double click the shortcut

If you need help with another issue, open another one. Thanks.
