### ISSUE TITLE
Error when compiling wallet for Ubuntu

### ISSUE THREAD

**Issue by yhyim** [EmberCoin/Ember#20]
Error when compiling wallet for Ubuntu

When I try to compile with below command
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
make -f makefile.unix
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

I got many Error like below
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
bitcoind.cpp: In function ‘bool AppInit(int, char**)’:
bitcoind.cpp:34:5: error: ‘argv0’ was not declared in this scope
     argv0 = argv[0];
     ^
bitcoind.cpp: In function ‘int main(int, char**)’:
bitcoind.cpp:130:2: error: ‘argv0’ was not declared in this scope
  argv0 = argv[0];
  ^
makefile.unix:192: recipe for target 'obj/bitcoind.o' failed
make: *** [obj/bitcoind.o] Error 1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I deleted two lines and passed......

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
net.cpp: In member function ‘bool CNode::RecvMsg(char*, int32_t)’:
net.cpp:134:32: error: ‘WSAECONNRESET’ was not declared in this scope
    if (!fDisconnect || nErr != WSAECONNRESET) {
                                ^
makefile.unix:192: recipe for target 'obj/net.o' failed
make: *** [obj/net.o] Error 1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
deleted || nErr != WSAECONNRESET then passed

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
obj/init.o: In function `boost::_bi::bind_t<void, void (*)(char const*, void (*)()), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<void (*)()> > >::bind_t(void (*)(char const*, void (*)()), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<void (*)()> > const&)':
/usr/include/boost/bind/bind.hpp:1158: undefined reference to `ThreadIRCSeed()'
collect2: error: ld returned 1 exit status
makefile.unix:206: recipe for target 'Emberd' failed
make: *** [Emberd] Error 1
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
I cannot fix this error

Please help me to build

**Comment by hitobb** [comment]
I have the same issue.
I tested some workarounds.

However,Only this error can not be resolved.

obj/init.o: In function boost::_bi::bind_t<void, void (*)(char const*, void (*)()), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<void (*)()> > >::bind_t(void (*)(char const*, void (*)()), boost::_bi::list2<boost::_bi::value<char const*>, boost::_bi::value<void (*)()> > const&)': /usr/include/boost/bind/bind.hpp:1158: undefined reference toThreadIRCSeed()'
collect2: error: ld returned 1 exit status
makefile.unix:206: recipe for target 'Emberd' failed
make: *** [Emberd] Error 1

**Comment by EmberCoin** [comment]
You're better off trying in the dev2 branch latest until tonight when we release all 3 or 4 wallets. It has the work of a person who builds on linux. Or you can wait until tomorrow when that work is mainlined into master.

**Comment by hitobb** [comment]
I succeeded in Emberd building using dev2 branch.
Thank you!

My environment is below:

> testuser@hostname:~$more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

**Comment by EmberCoin** [comment]
We have also just done a release based on the dev2 branch as well, official build and source are tagged: https://github.com/EmberCoin/Ember/releases/tag/v1.1.4

Thanks and hope you have a great day!

**Comment by tiendatvjc** [comment]
@hitobb  please can you teach me how to fix it? I got the same error when compile another coin

**Comment by hitobb** [comment]
git clone -b dev2 https://github.com/EmberCoin/Ember.git

sudo apt-get install build-essential
sudo apt-get install libssl-dev
sudo apt-get install libboost-all-dev
sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev
sudo apt-get install libdb4.8++-dev
sudo apt-get install libminiupnpc-dev 

then

Emberd building
