### ISSUE TITLE
IRC connect failed

### ISSUE THREAD

**Issue by bear-J** [EmberCoin/Ember#22]
I can't use Ember Wallet.

OS:Windows10
-----Error-----
irc thread start
ThreadIRCSeed started
updater: Downloading http://www.0xify.com/static/emb/win/x86/_latest_version.txt
IRC connect failed
IRC waiting 71 seconds to reconnect
updater: Error on dl attempt: (2).
updater: Download of http://www.0xify.com/static/emb/win/x86/_latest_version.txt failed: Connection closed
0 addresses found from DNS seeds
dnsseed thread exit
Adding fixed seed nodes as DNS doesn't seem to be available.
IRC connect failed
IRC waiting 138 seconds to reconnect
IRC connect failed
IRC waiting 211 seconds to reconnect
IRC connect failed
IRC waiting 292 seconds to reconnect
IRC connect failed
IRC waiting 381 seconds to reconnect

**Comment by EmberCoin** [comment]
You can, just grab a peers.dat from the discord, or https://www.0xify.com/static/peers.dat and put that in %appdata%\Ember\

**Comment by bear-J** [comment]
Synchronized. Thx.

**Comment by EmberCoin** [comment]
Take care!
