### ISSUE TITLE
Gradual downward sloping of reduction in payouts. Begins Nov. 1st at 0:00 UTC til 3 days later when the rate will be 720%.

### ISSUE THREAD

**Issue by vlast3k** [EmberCoin/Ember#23]
i hope you have time to answer, but somehow i couldn't find how this is implemented. In the master branch there is some code
```
int64_t GetProofOfStakeReward(int64_t nCoinAge, int64_t nFees) {
    int64_t nSubsidy = nCoinAge * 7200 * 1000000 * 33 / (365 * 33 + 8);
    //uint256 nSubsidyFactually =
    int64_t n = GetAdjustedTime();
    time_t past = APPROX(2017, 11, 0, 0, 0, 0);
    time_t future = APPROX(2017, 11, 3, 0, 0, 0);
    time_t far_future = APPROX(2018, 11, 0, 0, 0, 0);

    LogPrint("creation", "GetProofOfStakeReward(): create=%s nCoinAge=%d\n", FormatMoney(nSubsidy), nCoinAge);

    return nSubsidy + nFees;
}
```
but i can't understand how it would act ?
And the source that is attached to the 1.1.3 release looks like to be from the dev branch (though i didn't check exacty), but there the method is different

**Comment by EmberCoin** [comment]
Hello, the fully working implementation is in this release: https://github.com/EmberCoin/Ember/releases/tag/v1.1.4

Let me know if you have any issues by opening another issue.
