### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by sabecoin** [EmberCoin/Ember#26]
Hello, I am running the ember wallet on Debian Stretch. Everything is fine except there seems to be a bug causing the wallet CPU usage to fluctuate between 70 - 100%.

**Comment by EmberCoin** [comment]
Yes we're having a hard time tracking down the bug. There seem to be two threads with CPU spinning areas. 1 is RPC threads, the other I'm unable to determine yet as profilers on windows are in various stages of suck. There is also the usual high CPU when syncing but that is not an issue.

Most people experience one core pegging. I will update this issue as I work on it.

**Comment by sabecoin** [comment]
Ok thanks for your quick response.

Just to confirm, mine is one core only also.

**Comment by EmberCoin** [comment]
Okay, this only happens during block placement and sync anymore. Marking it closed.
