### ISSUE TITLE
RPC no longer functional after updating

### ISSUE THREAD

**Issue by presstab** [EmberCoin/Ember#28]
`ThreadRPCServer incorrect password attempt from ::ffff:<myipaddresshere>`

Also the blockchain seems to be stuck for me. Any suggestions?

**Comment by EmberCoin** [comment]
Restart the client with ` -rescan`

Let me know if you still still cannot access RPC once you are on the right blockchain and using v1.1.4. I can verify that RPC works fine once sync'd.

Will also need to see the RPC connection details (with identifiable info or passwords snipped) if you are unable to get it working correctly.

**Comment by EmberCoin** [comment]
You may need to use bootstrap over a new folder (with wallet.dat backed up and copied elsewhere) in order to help you out if the `-rescan` doesn't work. 

That bootstrap is here: https://drive.google.com/open?id=0B4PPmqI-4mwSVjJLU1UxRGtwaXM

**Comment by presstab** [comment]
Looks like something corrupted, or maybe an error in my .conf. It appears to be working after building clean.
