### ISSUE TITLE
Confirmation times are outrageous (4 hours on an exchange?)

### ISSUE THREAD

**Issue by EmberCoin** [EmberCoin/Ember#4]
[12:56 AM] ErGo: @___ Another to add to the review and fix list...That 100 coins deposit is still not confirmed. Why? Because it takes 200 confirmations to hit the exchange.  4 hours and that transfer is at 140/200

**Comment by aaashes** [comment]
Take a look at https://www.cryptopia.co.nz/api/GetCurrencies (DepositConfirmations":200), there's 200+ other coins which require 200 confirms too.
If we bought another one of these coins which has <20 nodes supporting the network too, we'd have similar delays.

See it as we have the following options:
1) To reduce confirm time to 2 hours we need to double. For 1 hour confirms, 80+ would be target. Ideally 30 minute confirms would be our main target with 160 nodes. To achieve this we could setup a bounty for a full node cluster or build a turn key distribution with accompanying documentation for users to easily setup their own full nodes. Second is preferred as it keeps the network for the most part fully decentralized, while the first results in more less full centralization.

**Comment by EmberCoin** [comment]
We've had our confirmation times reduced on Cryptotopia!
