### ISSUE TITLE
Still sync-problems on Linux and Windows

### ISSUE THREAD

**Issue by Himan2001** [EmberCoin/Ember#47]
Acording to the usual sync-problems on Linux and Windows i have seen,
that the Sync hangs mostly on a Blockchain that is generally up-to-date.
The Sync is starting again often only when a NEW block comes in.
By the actual slow blocktime it results in a few minutes delay to get in sync again.

I monitored Linux and Windows with the same config/peers and blockchain hight
directly after startup and booth daemons are hanging nearly 8 Minutes.
When a new valid block comes in, and booth systems was in sync in only 2 seconds.

By the way, at the time of "waiting for nothing" the load is always nearly 100%
- when staking is still off! (Problem described in another ticket)

**Comment by EmberCoin** [comment]
I expect this problem will resolve itself when the load problem is resolved. Refer to #44

**Comment by Himan2001** [comment]
I can confirm this problem on my linux-machine:
The load is way to high and the logfile shows enormous dropped network connections to the 
connected clients - this makes continous syncing unstable and unreliable.
I see that working nodes got as "tryed" connections to the peers.dat db and the daemon
search for other peers. Without limiting the maxconnections=15 i noted 1 time in my NAT-router
a NAT-table overflow a few days ago. The Router log showed more then 300 connection-attempts in a very short time, so the firewall considered this as an internal attack and blocked the communications.
