### ISSUE TITLE
maxconnections= still ignored on last version

### ISSUE THREAD

**Issue by Himan2001** [EmberCoin/Ember#51]
I noted, that the maxconnection-setting is still ignored.
I set maxconnections=20 - i got 35, i set 15, i got 22, i set 10 and i got 20 after few hours.
same result on linux and windows

**Comment by MPAds** [comment]
could some of the connections you are getting be due to other QT's you have running, or are you just running this one?

**Comment by Himan2001** [comment]
no its equal on the cli-daemon and the qt-version on linux and windows
you can check with netstat -antup under linux and see the connection+processname.
on windows this is netstat -ano
