### ISSUE TITLE
0 Active Connections to Ember Network

### ISSUE THREAD

**Issue by Rags111** [EmberCoin/Ember#55]
With the new wallet I am getting 0 Active Connections - see attached debug log
[debug.log](https://github.com/EmberCoin/Ember/files/1594540/debug.log)

**Comment by matheusvetor** [comment]
Seems ok now

**Comment by Rags111** [comment]
yes Ember Team in discord mentioned that it just takes time. Thanks to all the Ember Team for effort. Looking for a great 2018 with Ember
