### ISSUE TITLE
Embercoin.io still pointing to old git repo.

### ISSUE THREAD

**Issue by aaashes** [EmberCoin/Ember#8]
Having issues with comm channels, only able to access slack which is a ghost town. Can you or anyone viewing this, @ shegarn on #general in discord to replace the old git repo linked in main site to https://github.com/TheJuiceDidThis/Ember as the other is no longer maintained and this is the new main repo.

**Comment by EmberCoin** [comment]
This is currently blocked by #6 
Once we for sure have a good enough replacement we'll change it over.

**Comment by aaashes** [comment]
Ok, are we going to create a new git repo entirely under a new Embercoin related banner instead of our own accounts when we're content with the replacement? Would appear more professional.

**Comment by EmberCoin** [comment]
Yep. I'm going to change this account's name over to something more matching the project's spirit than my spirit. I put it up for discussion in the discord and so far it appears that we're going to go with Ember Coin, of course with matching avatar. It's a good thing this is a single use account!

**Comment by EmberCoin** [comment]
Delivered!
