### ISSUE TITLE
Approximation on Stake Time needs improving.

### ISSUE THREAD

**Issue by EmberCoin** [EmberCoin/Ember#9]
We receive a lot of feedback wondering why the estimated time went up or stalled. We need to calculate the approximation more astutely. Noting here for later once builds get going.

**Comment by aaashes** [comment]
If more people start to stake, the difficulty will increase and estimated time shall rise as a by product.
Not come across anything resembling stalling client side, so would be helpful if anyone experiencing this can explain in detail any accounts of this

**Comment by EmberCoin** [comment]
We switched away from a time based approach to actually failed attempts in getting a signed PoS block, so you see it actually attempt.
